name: local_notepad
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0  # Или ваша текущая версия
  fleather: ^1.0.0            # Или ваша текущая версия
  
  # Добавьте эти три строки:
  reorderableitemsview: ^1.0.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0


flutter:
  uses-material-design: true
