name: local_notepad
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.5
  fleather: ^1.27.0
  reorderable_grid_view: ^2.2.1

flutter:
  uses-material-design: true
